### ISSUE TITLE
Cannot read property 'reduce' of undefined 

### ISSUE THREAD

**Issue by siddo420** [primus/metroplex#14] opened 2016-03-19 13:39 UTC
I got this error when I tested sending msgs through primus.forward.sparks connected to separate instances

```
error: uncaughtException: Cannot read property 'reduce' of undefined date=...., cwd=/test3, ...
stack=[TypeError: Cannot read property 'reduce' of undefined,     at calculate (/test3/node_modules/metroplex/omega.js:73:24),     at done (/test3/node_modules/metroplex/node_modules/async/lib/async.js:167:19),     at /test3/node_modules/metroplex/node_modules/async/lib/async.js:40:16,     at calculate (/test3/node_modules/omega-supreme/supreme.js:188:7),     at /test3/node_modules/omega-supreme/node_modules/async/lib/async.js:251:17,     at /test3/node_modules/omega-supreme/node_modules/async/lib/async.js:200:33,     at /test3/node_modules/omega-supreme/node_modules/async/lib/async.js:248:21,     at Request.requested (/test3/node_modules/omega-supreme/supreme.js:177:9),     at Request.self.callback (/test3/node_modules/omega-supreme/node_modules/request/request.js:368:22),     at emitTwo (events.js:100:13),     at Request.emit (events.js:185:7),     at Request.<anonymous> (/test3/node_modules/omega-supreme/node_modules/request/request.js:1219:14),     at emitOne (events.js:95:20),     at Request.emit (events.js:182:7),     at IncomingMessage.<anonymous> (/test3/node_modules/omega-supreme/node_modules/request/request.js:1167:12),     at emitNone (events.js:85:20),     at IncomingMessage.emit (events.js:179:7),     at endReadableNT (_stream_readable.js:913:12),     at _combinedTickCallback (node.js:377:13),     at process._tickDomainCallback (node.js:425:11)]
```

**Comment by siddo420** [comment] 2016-03-19 13:42
Primus=5.0.1
Metroplex=~0.0.9
Omega-supreme=0.0.5

**Comment by 3rd-Eden** [comment] 2016-03-19 14:03
Do you have a test case that reproduces this bug

**Comment by siddo420** [comment] 2016-03-19 15:06
I think I found the issue in your code. 

Error message
```
Cannot read property 'reduce' of undefined,     at calculate (/test3/node_modules/metroplex/omega.js:73:24)
```

looking at the relevant lines
```
      async.each(Object.keys(servers), function each(server, next) {
        forward(server, msg, servers[server], next);
      }, function calculate(err, reached) {                       //<-- async.each callback
        if (err) return fn(err, reached);

        fn(err, reached.reduce(function reduce(memo, reach) {  //<-- line 73
          memo.send += reach.send || 0;
          return memo;
        }, { ok: true, send: 0 }));
      });
    });
```

A/c to async docs at https://github.com/caolan/async#eacharr-iteratee-callback and if I understood correctly, the .each callback only gets an error (no results array) as argument.

**Comment by siddo420** [comment] 2016-03-19 15:10
looks like I had an older version installed 

.each has been replaced with .map 

I will test it and report back or close (if needed).

**Comment by lpinca** [comment] 2016-03-19 16:56
@siddo420 the [fix](https://github.com/primus/metroplex/commit/1afdc8663e541b297123c24b14c00dc6eb267b11) you mention is not available on npm.
We had a breaking change in https://github.com/primus/metroplex/commit/9af8344b27d398f63564cb0b4b577ac43b5748d9 and we didn't publish a new version since then.

**Comment by lpinca** [comment] 2016-03-19 18:36
Should be fixed in the latest version, closing.

**Closed by lpinca** 2016-03-19 18:36 UTC
